name: coffee_app
description: "A new Flutter project."

version: 1.0.0+1

environment:
  sdk: '>=3.4.1 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: any


  cupertino_icons: ^1.0.6
  flutter_bloc: ^8.1.6
  equatable: ^2.0.5
  bloc: ^8.1.4
  http: ^1.2.1
  google_fonts: ^6.2.1
  font_awesome_flutter: ^10.7.0
  provider: ^6.1.2
  path_provider: ^2.1.3
  image: ^4.2.0
  nanoid: ^1.0.0
  shared_preferences: ^2.2.3
  

dev_dependencies:
  flutter_test:
    sdk: flutter

  intl_utils: ^2.8.7
  flutter_lints: ^3.0.0
  build_runner: ^2.4.11
  bloc_test: ^9.1.7
  mocktail: ^1.0.4
  mockito: ^5.4.4

flutter_intl:
  enabled: true
  arb_dir: lib/l10n
  output_dir: lib/l10n/generated
  class_name: S
  main_locale: en

flutter:
  generate: true
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
